version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app # creates volume like if project created inside container will also creates it here.
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"